### ISSUE TITLE
支持 async/await 么？

### ISSUE THREAD

**Issue by GreedBell** [MeCKodo/wxapp#1]
如果要支持`async/await`，按 [babel-plugin-transform-runtime](https://babeljs.io/docs/plugins/transform-runtime/) 上的用法 `dist` 中也应该依赖`babel-runtime` ，而你只是放在 `package.json`的`devDependencies` ，这样不支持 async/await 吧

**Comment by MeCKodo** [comment]
恩，并没有开放支持async

**Comment by GreedBell** [comment]
有没有可能用 npm 管理微信小程序依赖，把  babel-plugin-transform-runtime  依赖加进去？

**Comment by MeCKodo** [comment]
小程序的依赖？那个，请问你具体想要什么功能呢

**Comment by GreedBell** [comment]
找到了 [微信小程序开发三宗罪和解决方案](https://segmentfault.com/a/1190000007017985) 支持 async/await 谢谢了！

**Comment by MeCKodo** [comment]
其实想支持async很容易。。。我目前不想集成，很早以前就看了他的repo了😂
